# Site settings
title: Italy - 2017 Summer
subtitle: Family reunion
email: xiaozhuyfk@gmail.com
description:
baseurl: "/italy" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1728 Wightman Street
city: Pittsburgh
state: PA
zip_code: 15289
country: United States of America
phone: (818) 518-8712

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/xiaozhuyfk
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
